/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/animatedGentleman_fix.gltf -o src/components/AnimatedGentleman_fix.jsx -r public 
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function AnimatedGentleman_fix({isMoving, isJumping, isRunning, props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/animatedGentleman_fix.gltf')
  const { actions } = useAnimations(animations, group)
  const [animation, setAnimation] = useState("idle");

  useEffect(() => {
    const action = actions[animation];
    action.reset().fadeIn(0.32).play();
    return () => action?.fadeOut(0.32);
  }, [animation, actions]);

  useEffect(() => {
    if (isMoving) {
      if (isRunning) {
        setAnimation('run');
      } else {
        setAnimation('walk');
      }
    } else if (isJumping) {
      setAnimation('jump');
    } else {
      setAnimation('idle');
    }
  }, [isMoving, isJumping, isRunning]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="gentleman" scale={0.64}>
          <primitive object={nodes.LeftFootCtrl} />
          <primitive object={nodes.RightFootCtrl} />
          <primitive object={nodes.HipsCtrl} />
          <skinnedMesh name="characterMedium001" geometry={nodes.characterMedium001.geometry} material={materials['skin.003']} skeleton={nodes.characterMedium001.skeleton} castShadow/>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/animatedGentleman_fix.gltf')
